version: "2"
services:
    phinx:
        build:
            dockerfile: docker/Dockerfile
            context: .
        volumes:
            - .:/app
        links:
            - mysql:mysql
            - postgres:postgres
    mysql:
        image: mysql:5.5
        environment:
            - MYSQL_DATABASE=phinx_testing
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    postgres:
        image: postgres:9.2
        environment:
            - POSTGRES_DB=phinx_testing

